[package]
name = "ave-actors-actor"
version = "0.6.0"
edition.workspace = true
authors.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = { workspace = true }
borsh = { workspace = true }
dashmap = { workspace = true }
fastrand = { workspace = true }
memsecurity = { workspace = true }
prometheus-client = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros", "sync", "time"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
zeroize = { workspace = true }

[features]
prometheus = ["dep:prometheus-client"]

[dev-dependencies]
serde_json = "1.0"
test-log = { workspace = true }
